const title = [
  "How to create a website using HTML & Css |  Step-by-Step without any other library",
  "school dashboard with pure html css and javascript",
  "bobrisky latest news",
  "build & deploy a waste management app with gemini, tailwind & gemini",
  "installation of mac os on a hp laptop",
  "create a window 11 bootable device",
  "song that will never get old",
  "calendar shedualing with next js",
  "just my luck",
  "the language of network , http,smtp,dns e.tc",
  "mysql full course in 3hour",
  "create a fullstack website in just 30minute no coding",
  "functionality of cocacolar",
  "react in 100second",
  "vue in 100second",
  "javascript in 100second",
  "angular in 100second",
  "next in 100second",
  "fireship in 100second",
  "nest in 100second",
  "the best free window repair to fix any problems",
  "fullstack food delivery website",
  "clean & elegant vscode",
  "hack website password",
  "amazing restaurant website",
  "3d portfolio in three js",
  "build a real-time dashboard",
  "3real apps in 12 hours",
  "javascript full course",
  "spy on anyone",
  "sass website builder",
  "pandas full tutorial",
];

const fullname = [
  "FreeCodeCamp",
  "LunDev",
  "FireShip",
  "LamaDev",
  "TechGuy",
  "codeWithMosh",
  "BroCode",
  "HuxnWebDev",
  "telusko",
  "Jay",
  "Johnson",
  "Daniel",
  "MildredWood",
  "DeanKelley",
  "CordeliaEllis",
  "EmmaHouston",
  "ChristineSpencer",
  "RaymondGeorge",
  "BillHicks",
  "NathanMcDaniel",
  "MaxFrench",
  "SophieCurry",
  "MartinRobertson",
  "AlbertGonzales",
  "BernicePatterson",
  "SallyWilkins",
  "LydiaKim",
  "HenryThomas",
  "SallieCraig",
  "DeanHubbard",
  "AdaWatson",
  "ClarenceNunez",
  "RonaldCunningham",
  "LuluButler",
  "AllenTaylor",
  "DavidOwens",
  "MichealRobertson",
  "OpheliaGarner",
  "StephenLee",
  "SusanBell",
];

const selections = [
  "all",
  "computer science",
  "cybersecurity",
  "javascript",
  "java",
  "operating systems",
  "computer files",
  "music",
  "mobile app development",
  "gaming",
  "python",
  "security hackers",
  "live",
  "graphics design",
  "news",
  "afrobeat",
];

for (let i = 1; i < 600; i++) {
  console.log(
    `
      {
    id: ${i},
    poster_url: "/videos/video${i}.jpg",
    trailer: "/trailer/film${i}.webp",
    title: '${title[Math.floor(Math.random() * title.length)]}',
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum, cumque nemo itaque, doloremque vero sapiente accusantium quidem sed, molestias quisquam deleniti asperiores? Doloribus atque adipisci architecto sequi non necessitatibus accusantium temporibus commodi ipsa illo! Pariatur quasi voluptate voluptas, ex quo obcaecati ipsam omnis? Nemo itaque odit explicabo maiores cum a?",
      categories: '${
        selections[Math.floor(Math.random() * selections.length)]
      }',,
    user: {
      profile_pics: "/users/user${i}.jpg",
      full_name: '${fullname[Math.floor(Math.random() * fullname.length)]}',
      views: ${Math.floor(Math.random() * 9000)},
      date: "${Math.floor(Math.random() * 30)}-${Math.floor(
      Math.random() * 12
    )}-2023",
      like: ${Math.floor(Math.random() * 32000)},
      share: ${Math.floor(Math.random() * 900)},
    },
    `
  );
}
